#!/usr/bin/env bash

cd ~

apt update

git clone https://github.com/KhronosGroup/OpenCL-Headers.git
mv OpenCL-Headers/CL /usr/include/

apt install python-dev
apt install libboost-python-dev

git clone https://github.com/inducer/pyopencl.git
cd pyopencl
python3 -m pip install -e .

git clone https://github.com/tinygrad/tinygrad.git
cd ~/tinygrad
python3 -m pip install -e .
